spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: maxim277
    url: jdbc:postgresql://localhost:5432/fynotify

  flyway:
    encoding: UTF-8
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    username: polyakov
    password: maxim277
server:
  port: 8080


